/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */





declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  FloatFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Float
    divide?: number | null; // Float
    increment?: number | null; // Float
    multiply?: number | null; // Float
    set?: number | null; // Float
  }
  MovieCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    language: string; // String!
    medium_cover_image: string; // String!
    rating?: number | null; // Float
    summary: string; // String!
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  MovieUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    language?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    medium_cover_image?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    rating?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    summary?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  MovieWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  JustResponse: { // root type
    code: string; // String!
    message: string; // String!
  }
  Movie: { // root type
    id: number; // Int!
    language: string; // String!
    medium_cover_image: string; // String!
    rating: number; // Float!
    summary: string; // String!
    title: string; // String!
  }
  Mutation: {};
  Query: {};
  Response: { // root type
    code: string; // String!
    message: string; // String!
    movie: NexusGenRootTypes['Movie']; // Movie!
  }
  Subscription: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  JustResponse: { // field return type
    code: string; // String!
    message: string; // String!
  }
  Movie: { // field return type
    id: number; // Int!
    language: string; // String!
    medium_cover_image: string; // String!
    rating: number; // Float!
    summary: string; // String!
    title: string; // String!
  }
  Mutation: { // field return type
    addMovie: NexusGenRootTypes['Response']; // Response!
    createOneMovie: NexusGenRootTypes['Movie']; // Movie!
    deleteOneMovie: NexusGenRootTypes['Movie'] | null; // Movie
    updateOneMovie: NexusGenRootTypes['Movie'] | null; // Movie
  }
  Query: { // field return type
    getmovie: NexusGenRootTypes['Movie']; // Movie!
    getmovies: Array<NexusGenRootTypes['Movie'] | null>; // [Movie]!
    givemeError: string | null; // String
    movie: NexusGenRootTypes['Movie'] | null; // Movie
    movies: NexusGenRootTypes['Movie'][]; // [Movie!]!
    suggestions: Array<NexusGenRootTypes['Movie'] | null>; // [Movie]!
  }
  Response: { // field return type
    code: string; // String!
    message: string; // String!
    movie: NexusGenRootTypes['Movie']; // Movie!
  }
  Subscription: { // field return type
    movieDelete: NexusGenRootTypes['JustResponse']; // JustResponse!
  }
}

export interface NexusGenFieldTypeNames {
  JustResponse: { // field return type name
    code: 'String'
    message: 'String'
  }
  Movie: { // field return type name
    id: 'Int'
    language: 'String'
    medium_cover_image: 'String'
    rating: 'Float'
    summary: 'String'
    title: 'String'
  }
  Mutation: { // field return type name
    addMovie: 'Response'
    createOneMovie: 'Movie'
    deleteOneMovie: 'Movie'
    updateOneMovie: 'Movie'
  }
  Query: { // field return type name
    getmovie: 'Movie'
    getmovies: 'Movie'
    givemeError: 'String'
    movie: 'Movie'
    movies: 'Movie'
    suggestions: 'Movie'
  }
  Response: { // field return type name
    code: 'String'
    message: 'String'
    movie: 'Movie'
  }
  Subscription: { // field return type name
    movieDelete: 'JustResponse'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addMovie: { // args
      rating: number; // Int!
      title: string; // String!
    }
    createOneMovie: { // args
      data: NexusGenInputs['MovieCreateInput']; // MovieCreateInput!
    }
    deleteOneMovie: { // args
      where: NexusGenInputs['MovieWhereUniqueInput']; // MovieWhereUniqueInput!
    }
    updateOneMovie: { // args
      data: NexusGenInputs['MovieUpdateInput']; // MovieUpdateInput!
      where: NexusGenInputs['MovieWhereUniqueInput']; // MovieWhereUniqueInput!
    }
  }
  Query: {
    getmovie: { // args
      id: number; // Int!
    }
    getmovies: { // args
      limit?: number | null; // Int
      rating?: number | null; // Float
    }
    movie: { // args
      where: NexusGenInputs['MovieWhereUniqueInput']; // MovieWhereUniqueInput!
    }
    movies: { // args
      after?: NexusGenInputs['MovieWhereUniqueInput'] | null; // MovieWhereUniqueInput
      before?: NexusGenInputs['MovieWhereUniqueInput'] | null; // MovieWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    suggestions: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}